# This is a basic workflow to help you get started with Actions

name: issues reame list

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened, edited, closed, deleted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Auto Issue List in README
        # You may pin to the exact commit or the version.
        # uses: seed-of-apricot/issue-list-readme@55669b219cbd65d46522bd6dde3067b8d1df3c5f
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          # token
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          # pattern to detect the place to locate the table
          pattern: '<!-- issueTable -->'
          # comma-separated labels to filter the issues
          labels: 'idea'
          # state of the issues to filter them (open or closed)
          state: 'open'
